<?php

declare(strict_types=1);

namespace Domain\Service\Models;

use Domain\Blueprint\Models\Blueprint;
use Domain\Service\Enums\BillingCycleEnum;
use Domain\Taxonomy\Models\TaxonomyTerm;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Carbon;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Support\ConstraintsRelationships\Attributes\OnDeleteCascade;
use Support\ConstraintsRelationships\ConstraintsRelationships;
use Support\MetaData\Contracts\HasMetaData as HasMetaDataContract;
use Support\MetaData\HasMetaData;
use Support\MetaData\Models\MetaData;

/**
 * Domain\Service\Models\Service
 *
 * @property int $id
 * @property string $uuid
 * @property string $blueprint_id
 * @property string $name
 * @property string|null $description
 * @property float $retail_price
 * @property float $selling_price
 * @property BillingCycleEnum|null $billing_cycle
 * @property int|null $due_date_every
 * @property int $is_featured
 * @property int $is_special_offer
 * @property bool $pay_upfront
 * @property int $is_subscription
 * @property int $status
 * @property int $needs_approval
 * @property int $is_auto_generated_bill
 * @property int $is_partial_payment
// * @property int $is_installment
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \Spatie\Activitylog\Models\Activity> $activities
 * @property-read int|null $activities_count
 * @property-read Blueprint|null $blueprint
 * @property-read MediaCollection<int, Media> $media
 * @property-read int|null $media_count
 * @property-read MetaData|null $metaData
 * @property-read \Illuminate\Database\Eloquent\Collection<int, TaxonomyTerm> $taxonomyTerms
 *
 * @method static Builder|Service newModelQuery()
 * @method static Builder|Service newQuery()
 * @method static Builder|Service onlyTrashed()
 * @method static Builder|Service query()
 * @method static Builder|Service whereBillingCycle($value)
 * @method static Builder|Service whereBlueprintId($value)
 * @method static Builder|Service whereCreatedAt($value)
 * @method static Builder|Service whereDeletedAt($value)
 * @method static Builder|Service whereDescription($value)
 * @method static Builder|Service whereDueDateEvery($value)
 * @method static Builder|Service whereId($value)
 * @method static Builder|Service whereIsAutoGeneratedBill($value)
 * @method static Builder|Service whereIsFeatured($value)
// * @method static Builder|Service whereIsInstallment($value)
 * @method static Builder|Service whereIsPartialPayment($value)
 * @method static Builder|Service whereIsSpecialOffer($value)
 * @method static Builder|Service whereIsSubscription($value)
 * @method static Builder|Service whereName($value)
 * @method static Builder|Service whereNeedsApproval($value)
 * @method static Builder|Service wherePayUpfront($value)
 * @method static Builder|Service whereRetailPrice($value)
 * @method static Builder|Service whereSellingPrice($value)
 * @method static Builder|Service whereStatus($value)
 * @method static Builder|Service whereUpdatedAt($value)
 * @method static Builder|Service whereUuid($value)
 * @method static Builder|Service withTrashed()
 * @method static Builder|Service withoutTrashed()
 *
 * @mixin \Eloquent
 */
#[OnDeleteCascade(['metaData, taxonomyTerms'])]
class Service extends Model implements HasMedia, HasMetaDataContract
{
    use ConstraintsRelationships;
    use HasMetaData;
    use HasUuids;
    use InteractsWithMedia;
    use LogsActivity;
    use SoftDeletes;

    protected $fillable = [
        'uuid',
        'blueprint_id',
        'name',
        'description',
        'retail_price',
        'selling_price',
        'billing_cycle',
        'due_date_every',
        'is_featured',
        'is_special_offer',
        'pay_upfront',
        'is_subscription',
        'status',
        'needs_approval',
        'is_auto_generated_bill',
        'is_partial_payment',
        //        'is_installment',
    ];

    protected $casts = [
        'billing_cycle' => BillingCycleEnum::class,
        'is_featured' => 'bool',
        'is_special_offer' => 'bool',
        'pay_upfront' => 'bool',
        'is_subscription' => 'bool',
        'status' => 'bool',
        'needs_approval' => 'bool',
        'is_auto_generated_bill' => 'bool',
        'is_partial_payment' => 'bool',
        'is_installment' => 'bool',
        'retail_price' => 'float',
        'selling_price' => 'float',
    ];

    public function uniqueIds(): array
    {
        return ['uuid'];
    }
    //    protected $with = [
    //        'taxonomyTerms',
    //    ];

    /** @return \Illuminate\Database\Eloquent\Relations\BelongsToMany<\Domain\Taxonomy\Models\TaxonomyTerm> */
    public function taxonomyTerms(): BelongsToMany
    {
        return $this->belongsToMany(TaxonomyTerm::class, 'service_taxonomy_terms');
    }

    /** @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\Domain\Blueprint\Models\Blueprint, \Domain\Service\Models\Service> */
    public function blueprint(): BelongsTo
    {
        return $this->belongsTo(Blueprint::class);
    }

    public function defaultMetaData(): array
    {
        return [
            'title' => $this->name,
        ];
    }

    public function getRouteKeyName(): string
    {
        return 'uuid';
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logFillable()
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs();
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('media')
            ->useFallbackUrl('https://via.placeholder.com/500x300/333333/fff?text=No+preview+available')
            ->acceptsFile(fn () => [
                'video/*',
                'image/*',
            ]);
    }
}
