image: laravelsail/php81-composer:latest

definitions:
  setupScript: &setupScript composer install --prefer-dist --no-interaction &&
    cp .env.example .env &&
    php artisan key:generate
  steps:
    - step: &setup
        script:
          - *setupScript
        caches:
          - composer
    - step: &check-format
        <<: *setup
        name: Check Format
        script:
          - *setupScript
          - composer format-dry-run
        condition:
          changesets:
            includePaths:
              - "**.php"
              - "pint.json"
    - step: &analyse
        <<: *setup
        name: Analyse
        script:
          - *setupScript
          - composer analyse -- --memory-limit 256M
        caches:
          - composer
          - phpstan
        condition:
          changesets:
            includePaths:
              - "**.php"
              - "phpstan.neon.dist"
    - step: &test
        <<: *setup
        name: Test
        script:
          - *setupScript
          - composer test
  caches:
    phpstan: build/phpstan

pipelines:
  branches:
    master:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test

  pull-requests:
    "**":
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
