image:
  name: bitnami/laravel:11.3.3 # https://bitnami.com/stack/laravel w- 9.5.2 - 10.3.3
  run-as-user: 1000

definitions:
  caches:
    phpstan: build/phpstan
  setup-script: &setup-script |
    composer install --prefer-dist --no-interaction
    cp .env.testing .env
    php artisan key:generate
    php artisan about --only=environment
  steps:
    - step: &common-step
        caches:
          - composer
    - step: &check-format
        <<: *common-step
        name: Check Format
        script:
          - *setup-script
          - composer format-dry-run
        condition:
          changesets:
            includePaths:
              - "**.php"
              - "pint.json"
    - step: &analyse
        <<: *common-step
        name: Analyse
        script:
          - *setup-script
          - composer analyse-no-memory-limit
        caches:
          - composer
          - phpstan
        condition:
          changesets:
            includePaths:
              - "**.php"
              - "phpstan.neon"
              - "composer.json"
              - "bitbucket-pipelines.yml"
              - "phpstan-stubs/"
    - step: &test
        <<: *common-step
        name: Test
        size: 4x
        script:
          - *setup-script
          - composer test-ci

pipelines:
  branches:
    develop:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
    staging:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
      - step:
          <<: *common-step
          name: Deploy to Staging
          deployment: staging
          script:
            - *setup-script
            - composer require laravel/vapor-cli
            - ./vendor/bin/vapor deploy staging --commit="$BITBUCKET_COMMIT"
    master:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
      - step:
          <<: *common-step
          name: Deploy to Production
          deployment: production
          trigger: manual
          script:
            - *setup-script
            - composer require laravel/vapor-cli
            - ./vendor/bin/vapor deploy production --commit="$BITBUCKET_COMMIT"
    ecommerce-branch:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
          - step:
              <<: *common-step
              name: Deploy to Ecommerce Branch
              deployment: ecommerce
              services:
                - docker
              script:
                - *setup-script
                - composer global require laravel/vapor-cli --update-with-dependencies
                - ./vendor/bin/vapor deploy ecommerce-branch --commit="$BITBUCKET_COMMIT"
  pull-requests:
    "**":
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
