image:
  name: bitnami/laravel:10.3.3 # https://bitnami.com/stack/laravel
  run-as-user: 1000

definitions:
  caches:
    phpstan: build/phpstan
  setup-script: &setup-script |
    composer install --prefer-dist --no-interaction &&
    cp .env.example .env &&
    php artisan key:generate
    php artisan about --only=environment
  steps:
    - step: &common-step
        caches:
          - composer
    - step: &install-php-8.2
        name: Install PHP 8.2
        script:
          - apt-get update && apt-get install -y php8.2 php8.2-cli php8.2-common php8.2-json php8.2-opcache php8.2-mysql php8.2-mbstring php8.2-xml php8.2-gd php8.2-curl
    - step: &check-format
        <<: *common-step
        name: Check Format
        script:
          - *setup-script
          - composer format-dry-run
        condition:
          changesets:
            includePaths:
              - "**.php"
              - "pint.json"
    - step: &analyse
        <<: *common-step
        name: Analyse
        script:
          - *setup-script
          - composer analyse-no-memory-limit
        caches:
          - composer
          - phpstan
        condition:
          changesets:
            includePaths:
              - "**.php"
              - "phpstan.neon.dist"
    - step: &test
        <<: *common-step
        name: Test
        script:
          - *setup-script
          # TODO: remove test-no-timeout when using stancl/tenancy v4
          - composer test-no-timeout -- --ci --passthru-php="-d memory_limit=-1"

pipelines:
  branches:
    develop:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
    staging:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
      - step:
          <<: *common-step
          name: Deploy to Staging
          deployment: staging
          script:
            - *setup-script
            - composer require laravel/vapor-cli
            - ./vendor/bin/vapor deploy staging --commit="$BITBUCKET_COMMIT"
    master:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
      - step:
          <<: *common-step
          name: Deploy to Production
          deployment: production
          trigger: manual
          script:
            - *setup-script
            - composer require laravel/vapor-cli
            - ./vendor/bin/vapor deploy production --commit="$BITBUCKET_COMMIT"
    ecommerce-branch:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
          - step:
              <<: *common-step
              name: Deploy to Ecommerce Branch
              deployment: ecommerce
              script:
                - *setup-script
                - composer require laravel/vapor-cli
                - ./vendor/bin/vapor deploy ecommerce-branch --commit="$BITBUCKET_COMMIT"
  pull-requests:
    "**":
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
