image:
  name: bitnami/laravel:10.1.1
  run-as-user: 1000

definitions:
  caches:
    phpstan: build/phpstan
  setup-script: &setup-script |
    composer install --prefer-dist --no-interaction &&
    cp .env.example .env &&
    php artisan key:generate
  steps:
    - step: &common-step
        caches:
          - composer
    - step: &check-format
        <<: *common-step
        name: Check Format
        script:
          - *setup-script
          - composer format-dry-run
        condition:
          changesets:
            includePaths:
              - "**.php"
              - "pint.json"
    - step: &analyse
        <<: *common-step
        name: Analyse
        script:
          - *setup-script
          - composer analyse -- --memory-limit=-1
        caches:
          - composer
          - phpstan
        condition:
          changesets:
            includePaths:
              - "**.php"
              - "phpstan.neon.dist"
    - step: &test
        <<: *common-step
        name: Test
        script:
          - *setup-script
          - composer test -- --ci --passthru-php="-d memory_limit=-1"

pipelines:
  branches:
    develop:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
    staging:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
      - step:
          <<: *common-step
          name: Deploy to Staging
          deployment: staging
          script:
            - *setup-script
            - composer require laravel/vapor-cli
            - ./vendor/bin/vapor deploy staging --commit="$BITBUCKET_COMMIT"
    master:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
      - step:
          <<: *common-step
          name: Deploy to Production
          deployment: production
          trigger: manual
          script:
            - *setup-script
            - composer require laravel/vapor-cli
            - ./vendor/bin/vapor deploy production --commit="$BITBUCKET_COMMIT"
    ecommerce-branch:
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
          - step:
              <<: *common-step
              name: Deploy to Ecommerce Branch
              deployment: ecommerce
              script:
                - *setup-script
                - composer require laravel/vapor-cli
                - ./vendor/bin/vapor deploy ecommerce-branch --commit="$BITBUCKET_COMMIT"
                - php artisan tenants:migrate
  pull-requests:
    "**":
      - parallel:
          - step: *check-format
          - step: *analyse
          - step: *test
