<?php

declare(strict_types=1);

namespace Domain\Shipment\API\USPS\Enums;

enum Container: string
{
    case NONE = '';
    case VARIABLE = 'VARIABLE';
    case FLAT_RATE_ENVELOPE = 'FLAT RATE ENVELOPE';
    case PADDED_FLAT_RATE_ENVELOPE = 'PADDED FLAT RATE ENVELOPE';
    case LEGAL_FLAT_RATE_ENVELOPE = 'LEGAL FLAT RATE ENVELOPE';
    case SM_FLAT_RATE_ENVELOPE = 'SM FLAT RATE ENVELOPE';
    case WINDOW_FLAT_RATE_ENVELOPE = 'WINDOW FLAT RATE ENVELOPE';
    case GIFT_CARD_FLAT_RATE_ENVELOPE = 'GIFT CARD FLAT RATE ENVELOPE';
    case FLAT_RATE_BOX = 'FLAT RATE BOX';
    case SM_FLAT_RATE_BOX = 'SM FLAT RATE BOX';
    case MD_FLAT_RATE_BOX = 'MD FLAT RATE BOX';
    case LG_FLAT_RATE_BOX = 'LG FLAT RATE BOX';
    case REGIONALRATEBOXA = 'REGIONALRATEBOXA';
    case REGIONALRATEBOXB = 'REGIONALRATEBOXB';
    case REGIONALRATEBOXC = 'REGIONALRATEBOXC';
    case RECTANGULAR = 'RECTANGULAR';
    case NONRECTANGULAR = 'NONRECTANGULAR';
}
