<?php

declare(strict_types=1);

namespace Domain\Shipment\API\USPS\Enums;

enum ServiceType: string
{
    case FIRST_CLASS = 'FIRST CLASS';
    case FIRST_CLASS_COMMERCIAL = 'FIRST CLASS COMMERCIAL';
    case FIRST_CLASS_HFP_COMMERCIAL = 'FIRST CLASS HFP COMMERCIAL';
    case PRIORITY = 'PRIORITY';
    case PRIORITY_COMMERCIAL = 'PRIORITY COMMERCIAL';
    case PRIORITY_HFP_COMMERCIAL = 'PRIORITY HFP COMMERCIAL';
    case EXPRESS = 'EXPRESS';
    case EXPRESS_COMMERCIAL = 'EXPRESS COMMERCIAL';
    case EXPRESS_SH = 'EXPRESS SH';
    case EXPRESS_SH_COMMERCIAL = 'EXPRESS SH COMMERCIAL';
    case EXPRESS_HFP = 'EXPRESS HFP';
    case EXPRESS_HFP_COMMERCIAL = 'EXPRESS HFP COMMERCIAL';
    case PARCEL = 'PARCEL';
    case MEDIA = 'MEDIA';
    case LIBRARY = 'LIBRARY';
    case ALL = 'ALL';
    case ONLINE = 'ONLINE';
}
