<?php

declare(strict_types=1);

namespace Domain\Shipment\API\USPS\Constants;

final class Container
{
    /** Container constants */
    public const CONTAINER_VARIABLE = 'VARIABLE';
    public const CONTAINER_FLAT_RATE_ENVELOPE = 'FLAT RATE ENVELOPE';
    public const CONTAINER_PADDED_FLAT_RATE_ENVELOPE = 'PADDED FLAT RATE ENVELOPE';
    public const CONTAINER_LEGAL_FLAT_RATE_ENVELOPE = 'LEGAL FLAT RATE ENVELOPE';
    public const CONTAINER_SM_FLAT_RATE_ENVELOPE = 'SM FLAT RATE ENVELOPE';
    public const CONTAINER_WINDOW_FLAT_RATE_ENVELOPE = 'WINDOW FLAT RATE ENVELOPE';
    public const CONTAINER_GIFT_CARD_FLAT_RATE_ENVELOPE = 'GIFT CARD FLAT RATE ENVELOPE';
    public const CONTAINER_FLAT_RATE_BOX = 'FLAT RATE BOX';
    public const CONTAINER_SM_FLAT_RATE_BOX = 'SM FLAT RATE BOX';
    public const CONTAINER_MD_FLAT_RATE_BOX = 'MD FLAT RATE BOX';
    public const CONTAINER_LG_FLAT_RATE_BOX = 'LG FLAT RATE BOX';
    public const CONTAINER_REGIONALRATEBOXA = 'REGIONALRATEBOXA';
    public const CONTAINER_REGIONALRATEBOXB = 'REGIONALRATEBOXB';
    public const CONTAINER_REGIONALRATEBOXC = 'REGIONALRATEBOXC';
    public const CONTAINER_RECTANGULAR = 'RECTANGULAR';
    public const CONTAINER_NONRECTANGULAR = 'NONRECTANGULAR';
}
